[server]
port=5001  

[browser]
serverAddress="127.0.0.1"

[theme]
#base="light"
#primaryColor="#6eb52f"
#backgroundColor="#f0f0f5"
#secondaryBackgroundColor="#b3cbdd"
#textColor="#262730"
#font="serif"
#primaryColor="#6eb52f"
#backgroundColor="#f0f0f5"
#secondaryBackgroundColor="#e0e0ef"
#textColor="#262730"
font="monospace"
primaryColor="#d33682"
backgroundColor="#002b36"
secondaryBackgroundColor="#586e75"
textColor="#fafafa"

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
# base =

# Primary accent color for interactive elements.
# primaryColor =

# Background color for the main content area.
# backgroundColor =

# Background color used for the sidebar and most interactive widgets.
# secondaryBackgroundColor =

# Color used for almost all text.
# textColor =

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
# font =